services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ebra_db
      POSTGRES_USER: ebra
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ebra:password@db:5432/ebra_db
      WEBHOOK_URL: http://api:3000/api/v1/callbacks/call-status
      AI_PROVIDER_URL: http://api:3000/api/v1/provider
    volumes:
      - .:/app
    command: npm run dev

  worker:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ebra:password@db:5432/ebra_db
      WEBHOOK_URL: http://api:3000/api/v1/callbacks/call-status
      AI_PROVIDER_URL: http://api:3000/api/v1/provider
    volumes:
      - .:/app
    command: npm run worker

  studio:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ebra:password@db:5432/ebra_db
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: npx prisma studio --host 0.0.0.0 --port 5555

volumes:
  postgres_data:
