services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebra_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LOG_RETENTION_HOURS=1
      - KAFKA_LOG_LEVEL=FATAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LOG_LEVEL=FATAL
    ports:
      - "2181:2181"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - db
      - redis
      - kafka
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.docker

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./scripts/wait-for-kafka.sh", "npm", "run", "worker" ]
    depends_on:
      - db
      - redis
      - kafka
      - api
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.docker

volumes:
  db_data:
